version: '3'

services:

  database:
    image: mysql:5.7
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: compras
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpassword
    ports:
        - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
        - ./_Mysql_Init_Script/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - compras-network
    restart: always

  api-compras:
    image: api-compras
    build:
        context: .
    ports:
        - "8080:80"
    environment:
        DOTNET_ENVIRONMENT=Test
    networks:
        - compras-network
    depends_on:
        - "database"
    
networks: 
    compras-network:
        driver: bridge

volumes:
    dbdata: