version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
        - compras-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: compras
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpassword
    ports:
        - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
        - ./_Mysql_Init_Script/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - compras-network
    restart: on-failure

  api-compras:
    container_name: api-compras
    image: api-compras
    build:
        context: .
    ports:
        - "5000:80"
        - "5001:443"
    environment:
        DOTNET_ENVIRONMENT: Docker
    networks:
        - compras-network
    depends_on:
        - mysql
        - rabbitmq

networks: 
    compras-network:
        driver: bridge

volumes:
    dbdata: